hello:
  name: kly
  #随机字符串
  value: ${random.value}
  #随机int
  number: ${random.int}
  #随机long
  bignumber: ${random.long}
  #10以内的随机数
  test1: ${random.int(10)}
  #10~20的随机数
  test2: ${random.int[10,20]}